yolov10:
  version: m
  normalize_type: yolo
  load_model_type: yolo

  task_type: tracking

  tracker: DeepOcSort

  input_width: 1280
  input_height: 736

  bpp: 8
  box_threshold: 0.6

  weights:
    yolov10_tracker.pt:
      classes:
        - helmet
        - cyclist
        - headwear
      showed_classes:
        - helmet
        - cyclist
      tracked_classes:
        - helmet
        - cyclist

yolov11:
  version: m
  normalize_type: yolo
  load_model_type: yolo
  task_type: tracking

  tracker: DeepOcSort

  input_width: 1280
  input_height: 736

  bpp: 8
  box_threshold: 0.6

  weights:
    yolov11_tracker.pt:
      classes:
        - helmet
        - cyclist
        - headwear
      showed_classes:
        - helmet
        - cyclist
      tracked_classes:
        - helmet
        - cyclist
trackers:
  - DeepOcSort

templates:
  bikehelmets:
    architecture: yolov10
    weights: yolov10_tracker.pt
